type Album {
  id: ID!
  title: String
  image: String
  launchedAt: Float
  amountStickers: Int
  stickers: [Sticker]
  users: [User]
  amountFinishedSwaps: Int #ToCoding
}

input AlbumInput {
  title: String
  image: String
  launchedAt: Float
  approvedBy: ID
}

input AlbumToReviewInput {
  title: String
  image: String
  startSticker: Int
  finishSticker: Int
  reviewRequestedBy: ID
}

type Query {
  getAllAlbums: [Album]
  searchAlbum(searchTerm: String): [Album]
  getAlbumById(album: ID): Album
  getAllAlbumsToReview: [Album]
}

type Mutation {
  # Add album to database
  addAlbum(album: AlbumInput): Album
  addAlbumToReview(album: AlbumToReviewInput): Collection
}
