type Album {
  id: ID!
  title: String
  image: String
  launchedAt: Float
  amountStickers: Int #ToCoding
  stickers: [Sticker]
  users: [User] #ToCoding
  swaps: [Swap] #ToCoding
}
input AlbumInput {
  title: String
  image: String
  launchedAt: Float
  amountStickers: Int
}
type Query {
  getAllAlbums: [Album]
  searchAlbum(searchTerm: String): [Album]
  getAlbumById(album: ID): Album
}
type Mutation {
  # Add album to database
  addAlbum(album: AlbumInput): Album
}
