type stickerCollectionDetail {
  sticker: Sticker #ToCoding
  amount: Int
}

type Collection {
  id: ID!
  user: User #ToCoding
  album: Album #ToCoding
  stickersCollection: [stickerCollectionDetail]
  canHelpYou: [User] #ToCoding
}
