type stickerColectionDetail {
  sticker: Sticker #ToCoding
  amount: Int
}

type Colection {
  id: ID!
  user: User #ToCoding
  album: Album #ToCoding
  stickersColection: [stickerColectionDetail]
  canHelpYou: [User] #ToCoding
}
