type stickerCollectionDetail {
  sticker: Sticker
  amount: Int
}

type Collection {
  id: ID!
  album: Album
  stickersCollection: [stickerCollectionDetail]
  canHelpYou: [User] #ToCoding
}

input CollectionInput {
  user: ID
  album: ID
}

input addStickerToCollectionData {
  sticker: ID
  collection: ID
}

type Mutation {
  addCollection(collection: CollectionInput): Collection
  addStickerToCollection(operationDetail: addStickerToCollectionData): stickerCollectionDetail
  removeStickerToCollection(operationDetail: addStickerToCollectionData): stickerCollectionDetail
}
