type stickerCollectionDetail {
  sticker: Sticker #ToCoding
  amount: Int
}

type Collection {
  id: ID!
  album: Album
  stickersCollection: [stickerCollectionDetail]
  canHelpYou: [User] #ToCoding
}

input CollectionInput {
  user: ID
  album: ID
}

type Mutation {
  addCollection(collection: CollectionInput): Collection
}
