type stickerCollectionDetail {
  sticker: Sticker
  amount: Int
}

type Collection {
  id: ID!
  album: Album
  stickersCollection: [stickerCollectionDetail]
  canHelpYou: [User] #ToCoding
}

input CollectionInput {
  user: ID
  album: ID
}

input modifyStickerInCollectionData {
  sticker: ID
  collection: ID
  user: ID
}

input getCollectionByIdInput {
  collection: ID
  user: ID
}

type Mutation {
  addCollection(collection: CollectionInput): Collection
  addStickerToCollection(operationDetail: modifyStickerInCollectionData): stickerCollectionDetail
  removeStickerFromCollection(
    operationDetail: modifyStickerInCollectionData
  ): stickerCollectionDetail
}

type Query {
  getCollectionById(queryData: getCollectionByIdInput): Collection
}
