type Sticker {
  album: Album #ToCoding
  number: Int
  title: String
  image: String
  haveRepeated: [User] #ToCoding
}
input StickerInput {
  album: ID
  number: Int
  title: String
  image: String
}
type Mutation {
  addSticker(sticker: StickerInput): Sticker
}
