enum StateDetail {
  created
  accepted
  rejected
  changed
}

type State {
  state: StateDetail
  newStateBy: User
  changedAt: Float
}

type Swap {
  sentBy: User
  receivedBy: User
  states: [State]
  album: Album
  senderToReceiver: [Sticker]
  receiverToSender: [Sticker]
}
