type User {
  id: ID
  uid: String
  albums: [Album] #ToCoding
  collections: [Collection] #ToCoding
  ratings: [Rating] #ToCoding
  swaps: [Swap] #ToCoding
  distance: Int #ToCoding
}
input UserInput {
  uid: String
}
type Mutation {
  addUser(user: UserInput): User
}
