type User {
  id: ID
  uid: ID
  collections: [Collection] #Protect
  # albums: [Album] #ToCoding #BackLog
  albumsFilling: String
  ratings: [Rating]
  swaps: [Swap] #Protect
  distance: Int #ToCoding
  displayName: String
  profilePicture: String
  score: Float #ToCoding
  swapsWithMe: [Swap] #ToCoding #WithToken
  stickersUsefulToMe: [Sticker] #ToCoding #WithToken
  amountPosibleSwaps: Int #ToCoding #WithToken
}

input UserInput {
  uid: String
}

type Query {
  getUserById(user: ID): User
}

type Mutation {
  addUser(user: UserInput): User
}
