type User {
  uid: String
  albums: [Album] #ToCoding
  colections: [Colection] #ToCoding
  ratings: [Rating] #ToCoding
  swaps: [Swap] #ToCoding
  distance: Int #ToCoding
}
input UserInput {
  uid: String
}
type Mutation {
  addUser(user: UserInput): User
}
